<!-- #include file="ding.asp" -->
<!-- #include file="mymin.asp" -->
<%Call Head()%>
<%
response.write"<card title=""七色虎建站系统"">"
response.write"<p><img src=""logo.png"" alt=""七色虎建站系统""/>"
response.write"<br/>欢迎管理员:"&keyuser&""
response.write"<br/><a href=""class.asp?sid="&sid&""">设计中心</a> "
response.write"<a href=""config.asp?sid="&sid&""">网站配置</a><br/>"
response.write"【文章管理】<br/>"
response.write"<a href=""art/index.asp?sid="&sid&""">文章管理</a> "
response.write"<a href=""74hu/text.asp?sid="&sid&""">复制文章</a><br/>"
response.write"<a href=""art/wzcl.asp?sid="&sid&""">全部文章</a> "
response.write"<a href=""art/wzclass.asp?sid="&sid&""">分类管理</a><br/>"
response.write"<a href=""art/tjwz.asp?sid="&sid&""">添加分类</a> "
response.write"<a href=""art/adminpl.asp?sid="&sid&""">文章评论</a><br/>"
response.write"【站长工具】<br/>"
response.write"<a href=""74hu/files.asp?sid="&sid&""">文件管理</a> "
response.write"<a href=""74hu/wmltext.asp?sid="&sid&""">自写页面</a><br/>"
response.write"<a href=""bak.asp?sid="&sid&""">数据备份</a> "
response.write"<a href=""74hu/word.asp?sid="&sid&""">简繁互换</a><br/>"
response.write"<a href=""74hu/iplock.asp?sid="&sid&""">管理ＩＰ</a> "
response.write"<a href=""74hu/sql.asp?sid="&sid&""">注入攻击</a><br/>"
response.write"【高级管理】<br/>"
response.write"<a href=""ggao.asp?sid="&sid&""">广告管理</a> "
response.write"<a href=""gonggo.asp?sid="&sid&""">公告管理</a><br/>"
response.write"<a href=""link/mymin_index.asp?sid="&sid&""">友链管理</a> "
response.write"<a href=""lygl/index.asp?sid="&sid&""">留言管理</a><br/>"
response.write"<a href=""74hu/index.asp?sid="&sid&""">站长工具</a> "
response.write"<a href=""lltj.asp?sid="&sid&""">流量统计</a><br/>"
response.write"<a href=""guanli.asp?sid="&sid&""">管理设定</a> "
response.write"<a href=""logout.asp?sid="&sid&""">退出管理</a><br/>"
response.write"【使用帮助】<br/>"
response.write"<a href=""faq.asp?sid="&sid&""">常见问题</a> "
response.write"<a href=""http://74hu.cn"">更多帮助</a><br/>"
response.write"</p></card></wml>"%><%call CloseConn%>